<!-- Js -->            


<a id="showform" href="<?php echo $this->url('application', ['action'=>'showform']); ?>" data-toggle="modal" data-target="#winpopup">Show Form</a>
                    
<!-- empty div to save dialog temporary -->
<div class="modal fade" tabindex="-1" role="dialog" id="winpopup">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Loading...</h4>
      </div>
      <div class="modal-body">
        <div class="loader"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->