<script type="text/javascript">
    var is_xmlhttprequest = <?php echo $this->is_xmlhttprequest; ?>;
    var urlform           = '<?php echo $this->url('application', ['action'=>'validatepostajax']); ?>';
</script>
<?php echo $this->headScript()->appendFile($this->basePath() . '/js/ajaxform-up.js'); ?>

<?php
$title = 'Add Test';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('application', ['action'=>'showform']));
$form->get('cancel')->setLabel('Cancel');
$form->get('select')->setAttributes(['class'=>'form-control']);
$form->get('cancel')->setAttributes(['class'=>'btn']);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();
?>

<div class="modal-content">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title"><?php echo $this->escapeHtml($title); ?></h4>
	</div>
	<?php echo $this->form()->openTag($form); ?>
		<div class="modal-body">
			<?php echo $this->formRow($form->get('select')); ?>
		</div>
		<div class="modal-footer">
			<?php echo $this->formRow($form->get('cancel')); ?>
			<?php echo $this->formRow($form->get('submit')); ?>
		</div>
	<?php echo $this->form()->closeTag(); ?>
</div><!-- /.modal-content -->
